service:
  name: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs12.x
  
  # Enable X-Ray and iamRoleStatements for X-Ray
  tracing: 
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    TODOS_TABLE: ExampleDB
    TODOS_BUCKET: meowmeowbuckt
    INDEX_NAME: todosToday
    URL_EXPIRATION_TIME: 300
    AUTH_0_SECRET: process.env.AUTH_0_SECRET

# TODO: Configure custom item with documentation and request validator models
custom: ${file(./custom.json)}
  


functions:

  Auth:
    name: "Auth"
    handler: src/lambda/auth/auth0Authorizer.handler

  GetTodos:
    handler: src/lambda/http/businessLayer/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
          - xray:PutTraceSegments
        Resource:
          - "*"

  CreateTodo:
    name: "createtodo"
    handler: src/lambda/http/businessLayer/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
          # TODO: Configure documentation, reqValidatorName, and methodResponses
          documentation:
            summary: "Validate requests"
            description: "validates all request bodies for field and type"
            requestModels:
              "applicaton/json": ${self:custom.documentation.models.CreateTodoRequests}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - xray:PutTraceSegments
        Resource:
          - "*"
  
  UpdateTodo:
    name: "updatetodo"
    handler: src/lambda/http/businessLayer/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer: Auth
          # TODO: Configure documentation, reqValidatorName, and methodResponses
          documentation:
            summary: "Validate requests"
            description: "validates all request bodies for field and type"
            requestModels:
              "applicaton/json": ${self:custom.documentation.models.UpdateTodoRequests}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - xray:PutTraceSegments
        Resource:
          - "*"

  DeleteTodo:
    handler: src/lambda/http/businessLayer/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
          - xray:PutTraceSegments
        Resource:
          - "*"

  GenerateUploadUrl:
    handler: src/lambda/http/businessLayer/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
          - s3:GetObject
          - dynamodb:UpdateItem
          - xray:PutTraceSegments
        Resource:
          - "*"

resources:
  Resources:

    # Create a RequestValidator resource from ApiGateway
    RequestValidatorUpdate:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: "requestvalidatorupdate"
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    RequestValidatorCreate:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: "requestvalidatorcreate"
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    ExampleBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.TODOS_BUCKET}
        CorsConfiguration:
          CorsRules: 
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
              AllowedOrigins: ["*"]
    
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument: 
          Id: MyBucketMyRules
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::${self:provider.environment.TODOS_BUCKET}/*"
        Bucket: !Ref ExampleBucket

    ExampleDB:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "todoId"
            AttributeType: "S"
          - AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "userId"
            KeyType: HASH
          - AttributeName: "todoId"
            KeyType: RANGE 
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TODOS_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - AttributeName: "userId"
                KeyType: HASH
            Projection:
              ProjectionType: ALL